// <auto-generated>
// Generated by DialogueGenerator. Changes may be overwritten.

public enum Opinion
{
    negative = -1,
    neutral = 0,
    positive = 1,
}
public enum LevelIntro
{
    introStage1,
}

public enum AfterLevel
{
    afterFirstDrive,
    afterStage0,
}

